# Nome da aplicação
spring.application.name=clipper

# Configuração do CORS em DEVELOPMENT
app.cors.allowed-origin=http://localhost:5173

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clipper

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Exibe SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
