spring.application.name=clipper-helpdesk
spring.datasource.url=jdbc:postgresql://localhost:5432/clipper_helpdesk
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
